function checks = Validators()
%VALIDATORS  Assert derived constants obey their defining physics relations.
%
%   checks = physics.Validators() returns a struct array with fields:
%       .name  - human-readable description of the check
%       .got   - value produced by physics.Constants()
%       .want  - value required by the defining relation
%       .tol   - allowed absolute difference
%       .pass  - logical (|got-want| <= tol)
%
%   This enforces CLAUDE.md Rule 1 the RIGHT way: it checks RELATIONSHIPS
%   (range_per_sample must equal c/(2*fs)) and physical PLAUSIBILITY bands,
%   rather than asserting hard-coded "magic" values. A magic constant that
%   drifted out of its derivation would fail here.
%
%   Used by tests/Stage4_Test.m (physics-correctness pass, POA claim C3).

    C = physics.Constants();

    % helper to build one check row
    k = @(name, got, want, tol) struct( ...
            'name', name, 'got', got, 'want', want, 'tol', tol, ...
            'pass', abs(got - want) <= tol);

    checks = [ ...
        k('range_per_sample == c/(2*fs)',        C.range_per_sample, C.c/(2*C.fs),               1e-6); ...
        k('range_window     == N*range_per_sample', C.range_window,   C.Nsamples*C.range_per_sample, 1e-6); ...
        k('Rua_min          == c*PRI_min/2',      C.Rua_min,          C.c*C.PRI_min/2,             1e-6); ...
        k('Rua_max          == c*PRI_max/2',      C.Rua_max,          C.c*C.PRI_max/2,             1e-6); ...
        k('Ts               == 1/fs',             C.Ts,               1/C.fs,                      1e-15); ...
        % --- physical plausibility bands (bool -> 1 means "inside band") ---
        k('range_per_sample in [40,50] m',   double(C.range_per_sample>=40   && C.range_per_sample<=50),   1, 0); ...
        k('range_window     in [22,26] km',  double(C.range_window>=22e3     && C.range_window<=26e3),     1, 0); ...
        k('Rua_min          in [2.4,2.7] km',double(C.Rua_min>=2.4e3         && C.Rua_min<=2.7e3),         1, 0); ...
        k('Rua_max          in [3.3,3.6] km',double(C.Rua_max>=3.3e3         && C.Rua_max<=3.6e3),         1, 0); ...
    ];
end
