% scene_contract.m
% MATLAB mirror of cogengine/schema.py — the data contract across the boundary.
% These constructors document the exact fields each struct must carry so the
% Python engine and the MATLAB pipeline agree byte-for-byte.
%
% Design doc: Part 4 (Data contracts).

function s = radarStateStruct()
    s = struct( ...
        'mode',         "track", ...
        'prf_hz',       50e3, ...
        'carrier_hz',   10e9, ...      % assumed carrier (RadChar is baseband)
        'fs_hz',        3.2e6, ...     % matches RadChar
        'n_pulses',     512, ...
        'n_fast',       512, ...
        'range_gate_m', [0 3000], ...
        'vel_gate_mps', [-375 375], ...
        'scan_phase',   0.0, ...
        'doubt_cue',    0.0);
end

function p = phantomStruct()
    p = struct( ...
        'cls',            "drone", ...     % drone|fighter|airliner|missile|decoy
        'range_m',        1000.0, ...
        'radial_vel_mps', 30.0, ...
        'accel_mps2',     0.0, ...
        'rcs_dbsm',       0.0, ...
        'swerling',       1, ...           % 0 | 1/2 Rayleigh | 3/4 chi-sq-4
        'micro',          struct('type',"propeller",'n_blades',2,'rpm',12000,'blade_len_m',0.12), ...
        'amp_scale',      1.0);
end

function sc = sceneStruct()
    sc = struct( ...
        'phantoms',        phantomStruct(), ...   % array of phantomStruct
        'maneuver',        "swarm", ...           % static|rgpo|vgpo|swarm
        'eirp_budget_dbw', 10.0, ...
        't0_s',            0.0, ...
        'duration_s',      0.05);
end

function fb = feedbackStruct()
    % Produced by the INDEPENDENT judge (phased.CFARDetector + trackerGNN + ECCM)
    % and passed back to the engine's learn step (estimator.system_id).
    fb = struct( ...
        'confirmed_tracks',           0, ...
        'false_tracks_surviving',     0, ...   % <- primary deception metric
        'flagged_decoys',             0, ...
        'mean_track_lifetime_frames', 0.0, ...
        'eirp_used_dbw',              0.0, ...
        'per_phantom_status',         strings(0));  % undetected|detected|confirmed|flagged
end
